# Generated by Django 5.0.2 on 2024-03-20 05:26

import apps.trips.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_truck'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='addedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='btc_registrar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batch',
            name='editedBy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='btc_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(default=apps.trips.models.dtime)),
                ('loadPoint', models.CharField(max_length=255)),
                ('loadDate', models.DateField()),
                ('cargoWeight', models.FloatField()),
                ('startDate', models.DateField()),
                ('destination', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('completeDate', models.DateField()),
                ('describe', models.TextField(default=None, null=True)),
                ('lastEdited', models.DateTimeField(default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trp_registrar', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trp_batch', to='trips.batch')),
                ('editedBy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trp_editor', to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trp_truck', to='fleet.truck')),
            ],
        ),
    ]
