# Generated by Django 5.0.2 on 2024-03-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_batch_addedby_alter_batch_editedby_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='loadDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
