# Generated by Django 5.0.2 on 2024-03-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_loaddate_alter_trip_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='completeDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
