# Generated by Django 4.1.7 on 2024-03-21 12:09

import apps.trips.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0004_alter_trip_completedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(default=apps.trips.models.dtime)),
                ('statusdate', models.DateField()),
                ('tripstatus', models.CharField(max_length=255)),
                ('newposition', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hist_registrar', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hist_trip', to='trips.trip')),
            ],
        ),
    ]
