# Generated by Django 4.1.7 on 2024-03-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_history',
            name='trip',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='hist_trip', to='trips.trip'),
            preserve_default=False,
        ),
    ]
