# Generated by Django 4.1.7 on 2024-03-23 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_truck'),
        ('trips', '0006_alter_trip_history_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trp_driver', to='fleet.truck_driver'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trailer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trp_trailer', to='fleet.trailer'),
        ),
    ]
