# Generated by Django 5.0.2 on 2024-03-14 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('phone', models.CharField(default=None, max_length=10, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('password_changed', models.BooleanField(default=False)),
                ('description', models.TextField(default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_users', to='auth.permission')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbase.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
