# Generated by Django 5.0.2 on 2024-03-16 11:17

import apps.fleet.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(default=apps.fleet.models.dtime)),
                ('regnumber', models.CharField(max_length=16)),
                ('trailerType', models.CharField(max_length=64)),
                ('describe', models.TextField(default=None, null=True)),
                ('lastEdited', models.DateTimeField(default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrar', to=settings.AUTH_USER_MODEL)),
                ('editedBy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
